---
name: Release
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
jobs:
  push:
    name: Push
    if: github.repository == 'supercaracal/aws-ecr-image-pull-secret-controller'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency: aws-ecr-image-pull-secret-controller
    permissions:
      packages: write
    env:
      IMAGE_NAME: aws-ecr-image-pull-secret-controller
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
